# Generated by Django 4.2.4 on 2023-12-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creator',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='hour',
            field=models.TimeField(default='16:39'),
        ),
    ]
