# Generated by Django 4.2.4 on 2023-12-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_alter_comment_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='hour',
            field=models.TimeField(default='17:17'),
        ),
    ]
