# Generated by Django 4.2.4 on 2023-12-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_video_dislikes_alter_comment_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='hour',
            field=models.TimeField(default='20:52'),
        ),
        migrations.AlterField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
