# Generated by Django 4.2.4 on 2023-12-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0017_video_description_alter_comment_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='listed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='hour',
            field=models.TimeField(default='02:09'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
